/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulacoesRouteImport } from './routes/_app.simulacoes'
import { Route as AppPedidosRouteImport } from './routes/_app.pedidos'
import { Route as AppNegociacoesRouteImport } from './routes/_app.negociacoes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAprovacoesRouteImport } from './routes/_app.aprovacoes'
import { Route as AppSimulacoesIdRouteImport } from './routes/_app.simulacoes.$id'
import { Route as AppPedidosIdRouteImport } from './routes/_app.pedidos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulacoesRoute = AppSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppNegociacoesRoute = AppNegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulacoesIdRoute = AppSimulacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSimulacoesRoute,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/negociacoes': typeof AppNegociacoesRoute
  '/pedidos': typeof AppPedidosRouteWithChildren
  '/simulacoes': typeof AppSimulacoesRouteWithChildren
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/simulacoes/$id': typeof AppSimulacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/negociacoes': typeof AppNegociacoesRoute
  '/pedidos': typeof AppPedidosRouteWithChildren
  '/simulacoes': typeof AppSimulacoesRouteWithChildren
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/simulacoes/$id': typeof AppSimulacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/aprovacoes': typeof AppAprovacoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/negociacoes': typeof AppNegociacoesRoute
  '/_app/pedidos': typeof AppPedidosRouteWithChildren
  '/_app/simulacoes': typeof AppSimulacoesRouteWithChildren
  '/_app/pedidos/$id': typeof AppPedidosIdRoute
  '/_app/simulacoes/$id': typeof AppSimulacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aprovacoes'
    | '/dashboard'
    | '/negociacoes'
    | '/pedidos'
    | '/simulacoes'
    | '/pedidos/$id'
    | '/simulacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aprovacoes'
    | '/dashboard'
    | '/negociacoes'
    | '/pedidos'
    | '/simulacoes'
    | '/pedidos/$id'
    | '/simulacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/aprovacoes'
    | '/_app/dashboard'
    | '/_app/negociacoes'
    | '/_app/pedidos'
    | '/_app/simulacoes'
    | '/_app/pedidos/$id'
    | '/_app/simulacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulacoes': {
      id: '/_app/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof AppSimulacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/negociacoes': {
      id: '/_app/negociacoes'
      path: '/negociacoes'
      fullPath: '/negociacoes'
      preLoaderRoute: typeof AppNegociacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aprovacoes': {
      id: '/_app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulacoes/$id': {
      id: '/_app/simulacoes/$id'
      path: '/$id'
      fullPath: '/simulacoes/$id'
      preLoaderRoute: typeof AppSimulacoesIdRouteImport
      parentRoute: typeof AppSimulacoesRoute
    }
    '/_app/pedidos/$id': {
      id: '/_app/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof AppPedidosRoute
    }
  }
}

interface AppPedidosRouteChildren {
  AppPedidosIdRoute: typeof AppPedidosIdRoute
}

const AppPedidosRouteChildren: AppPedidosRouteChildren = {
  AppPedidosIdRoute: AppPedidosIdRoute,
}

const AppPedidosRouteWithChildren = AppPedidosRoute._addFileChildren(
  AppPedidosRouteChildren,
)

interface AppSimulacoesRouteChildren {
  AppSimulacoesIdRoute: typeof AppSimulacoesIdRoute
}

const AppSimulacoesRouteChildren: AppSimulacoesRouteChildren = {
  AppSimulacoesIdRoute: AppSimulacoesIdRoute,
}

const AppSimulacoesRouteWithChildren = AppSimulacoesRoute._addFileChildren(
  AppSimulacoesRouteChildren,
)

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNegociacoesRoute: typeof AppNegociacoesRoute
  AppPedidosRoute: typeof AppPedidosRouteWithChildren
  AppSimulacoesRoute: typeof AppSimulacoesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNegociacoesRoute: AppNegociacoesRoute,
  AppPedidosRoute: AppPedidosRouteWithChildren,
  AppSimulacoesRoute: AppSimulacoesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
